export const ActionTypes = {
    // Auth
    LOGOUT: 'LOGOUT',
    WAIT: 'WAIT',
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    PUT_USER_DATA: 'PUT_USER_DATA',
    CREATE_FOOD: 'CREATE_FOOD',
    GET_ALL_FOODS: 'GET_ALL_FOODS',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_FAIL: 'REGISTER_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
};
